In [1]:
import numpy as np

In [86]:
class TicTacToe():
    def __init__(self):
        self.reset()
    
    def reset(self):
        self.state = [0]*9
        self.turn = 1
        self.done = False
        return self.state
        
    def render(self):
        return np.array(self.state).reshape(3,3)
        
    def is_winner(self):
        s = self.state
        for i in range(3):
            if all([x==self.turn for x in [s[i], s[3+i], s[6+1]]]):
                return True
            if all([x==self.turn for x in s[3*i:3*i+3]]):
                return True
        if all([x==self.turn for x in [s[0], s[4], s[8]]]):
            return True
        if all([x==self.turn for x in [s[2], s[4], s[6]]]):
            return True
        return False
        
    def step(self,act):
        rew = 0
        s = self.state
        if s[act] != 0:
            rew = -1
            self.done = True
        else:
            s[act] = self.turn
            if self.is_winner():
                rew = 1
                self.done = True
            else:
                self.turn = -self.turn
        return self.render(),self.done,rew
            
    

In [87]:
env = TicTacToe()

In [88]:
env.reset()

[0, 0, 0, 0, 0, 0, 0, 0, 0]

In [89]:
env.step(4)

(array([[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]),
 False,
 0)

In [90]:
env.step(1)

(array([[ 0, -1,  0],
        [ 0,  1,  0],
        [ 0,  0,  0]]),
 False,
 0)

In [91]:
env.step(3)
env.step(0)
env.step(5)

(array([[-1, -1,  0],
        [ 1,  1,  1],
        [ 0,  0,  0]]),
 True,
 1)